redis:
  dbAddress: [ redis:6379 ] #redis地址 单机时，填写一个地址即可，使用redis集群时候，填写集群中多个节点地址（主从地址都可以填写，增加容灾能力），默认即可
  dbMaxIdle: 128
  dbMaxActive: 0
  dbIdleTimeout: 120
  dbUserName:  #only redis version 6.0+ need username
  dbPassWord: 123456  #redis密码 建议修改
  enableCluster: false #如果外部redis以集群方式启动，需要打开此开关
